---
Title: "Replication of Chou 2016 (Study 5) - Economic Insecurity Increases Physical Pain"
Author: "Sean Zion"
Date: "November 23rd, 2017"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

```{r Load Packages, echo=FALSE}
library(ggplot2)
library(tidyverse)
library(knitr)
library(ggthemes)
library(psych)
```

##Introduction

##Methods

###Planned Sample
###Materials

###Procedure

**Working Replication Links:**
 LINK
 

###Analysis Plan

**Analysis Steps**

##Results

###Data preparation

###Confirmatory analysis

###Exploratory analyses

Any follow-up analyses desired (not required).  


## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.

